openapi: 3.0.0 #versi OpenAPI yang digunakan

info:
  title: Pinjam Buku
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in : body
    name : body
    desription : Data pinjaman yang akan ditambahkan
    required : true
    schema:
      $ref : '#/definitions/Pinjaman'
  
responses:
  200:
    description : Pinjaman berhasil dilakukan
    schema :
      $ref : '#/definitions/Pinjaman'

  definitions :
    Pinjaman :
      type : object
      properties :
        id_book:
          type: integer
        user_id:
          type: string
        borrow_date:
          type: string
          format: date
        return_date:
          type: string
          format: date
      required:
        - id_book
        - user_id
        - borrow_date
        - return_date
