openapi: 3.0.0
info:
  title: Hapus Data Buku
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: id
    in: path
    description: ID buku yang ingin dihapus
    required: true
    type: integer
responses:
  200:
    description: Data buku berhasil dihapus
  404:
    description: Data tidak ditemukan