openapi: 3.0.0
info:
  title: Ambil Satu Data Pinjaman
  version: 1.0.0
tags:
  - name: Daftar API
definitions:
  Pinjaman:
    type: object
    properties:
      id:
        type: integer      
      id_book:
        type: integer
      user_id:
        type: string
      borrow_date:
        type: string
        format: date
      return_date:
        type: string
        format: date

parameters:
  - name: id
    in: path
    description: ID pinjaman yang ingin ditampilkan
    required: true
    type: integer

responses:
  200:
    descriptions: Daftar semua pinjaman
    schema:
      type: array
      items:
        $ref: '#/definitions/Pinjaman'